language: python

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - FLASK="==0.8" PUSHER="pusher<1.0"
  - FLASK="==0.8"
  - FLASK="==0.9" PUSHER="pusher<1.0"
  - FLASK="==0.9"
  - FLASK="==0.10.1" PUSHER="pusher<1.0"
  - FLASK="==0.10.1" PUSHER="pusher>=1.0,<1.1"
  - FLASK="==0.10.1" PUSHER="pusher>=1.1,<1.2"
  - FLASK="==0.10.1" PUSHER="pusher>=1.2,<1.3"
  - FLASK="==0.10.1" PUSHER="pusher>=1.3,<1.4"
  - FLASK="==0.10.1" PUSHER="pusher>=1.4,<1.5"
  - FLASK="==0.10.1" PUSHER="pusher>=1.5,<1.6"
  - FLASK="==0.10.1" PUSHER="pusher>=1.6,<1.7"
  - FLASK="==0.10.1" PUSHER="pusher>=1.7,<1.8"
  - FLASK="==0.10.1" PUSHER="pusher>=2.0,<2.1"
  - FLASK="==0.10.1"
  - FLASK="==0.10.1" PUSHER="git+https://github.com/pusher/pusher-http-python.git"
  - FLASK="==0.11.1" PUSHER="pusher<1.0"
  - FLASK="==0.11.1" PUSHER="pusher>=1.0,<1.1"
  - FLASK="==0.11.1" PUSHER="pusher>=1.1,<1.2"
  - FLASK="==0.11.1" PUSHER="pusher>=1.2,<1.3"
  - FLASK="==0.11.1" PUSHER="pusher>=1.3,<1.4"
  - FLASK="==0.11.1" PUSHER="pusher>=1.4,<1.5"
  - FLASK="==0.11.1" PUSHER="pusher>=1.5,<1.6"
  - FLASK="==0.11.1" PUSHER="pusher>=1.6,<1.7"
  - FLASK="==0.11.1" PUSHER="pusher>=1.7,<1.8"
  - FLASK="==0.11.1" PUSHER="pusher>=2.0,<2.1"
  - FLASK="==0.12.4"
  - FLASK="==0.12.4" PUSHER="git+https://github.com/pusher/pusher-http-python.git"
  - FLASK="==0.12.4" PUSHER="pusher<1.0"
  - FLASK="==0.12.4" PUSHER="pusher>=1.0,<1.1"
  - FLASK="==0.12.4" PUSHER="pusher>=1.1,<1.2"
  - FLASK="==0.12.4" PUSHER="pusher>=1.2,<1.3"
  - FLASK="==0.12.4" PUSHER="pusher>=1.3,<1.4"
  - FLASK="==0.12.4" PUSHER="pusher>=1.4,<1.5"
  - FLASK="==0.12.4" PUSHER="pusher>=1.5,<1.6"
  - FLASK="==0.12.4" PUSHER="pusher>=1.6,<1.7"
  - FLASK="==0.12.4" PUSHER="pusher>=1.7,<1.8"
  - FLASK="==0.12.4" PUSHER="pusher>=2.0,<2.1"
  - FLASK="==0.12.4"
  - FLASK="==0.12.4" PUSHER="git+https://github.com/pusher/pusher-http-python.git"
  - FLASK="==1.0.2"
  - FLASK="==1.0.2" PUSHER="git+https://github.com/pusher/pusher-http-python.git"
  - FLASK="==1.0.2" PUSHER="pusher<1.0"
  - FLASK="==1.0.2" PUSHER="pusher>=1.0,<1.1"
  - FLASK="==1.0.2" PUSHER="pusher>=1.1,<1.2"
  - FLASK="==1.0.2" PUSHER="pusher>=1.2,<1.3"
  - FLASK="==1.0.2" PUSHER="pusher>=1.3,<1.4"
  - FLASK="==1.0.2" PUSHER="pusher>=1.4,<1.5"
  - FLASK="==1.0.2" PUSHER="pusher>=1.5,<1.6"
  - FLASK="==1.0.2" PUSHER="pusher>=1.6,<1.7"
  - FLASK="==1.0.2" PUSHER="pusher>=1.7,<1.8"
  - FLASK="==1.0.2" PUSHER="pusher>=2.0,<2.1"
  - FLASK="==1.0.2"
  - FLASK="==1.0.2" PUSHER="git+https://github.com/pusher/pusher-http-python.git"
matrix:
  exclude:
    - python: 3.6
      env: FLASK="==0.8" PUSHER="pusher<1.0"

install:
  - pip install Flask$FLASK $PUSHER
  - pip install unittest2 coverage coveralls
  - python setup.py install

script:
  - coverage run --source=flask_pusher setup.py test

after_success:
  - coveralls

